# Generated by the gRPC Python protocol compiler. DO NOT EDIT!
"""gRPC client definitions for documentation.embeddings."""

import grpc

from documentation import embeddings_pb2 as embeddings__pb2


class EmbeddingServiceStub:
    def __init__(self, channel):
        self.EmbedQuery = channel.unary_unary(
            "/documentation.embeddings.EmbeddingService/EmbedQuery",
            request_serializer=embeddings__pb2.EmbedRequest.SerializeToString,
            response_deserializer=embeddings__pb2.EmbedResponse.FromString,
        )
        self.EmbedDocument = channel.unary_unary(
            "/documentation.embeddings.EmbeddingService/EmbedDocument",
            request_serializer=embeddings__pb2.EmbedRequest.SerializeToString,
            response_deserializer=embeddings__pb2.EmbedResponse.FromString,
        )
