# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Protocol buffer definitions for documentation.embeddings."""

from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1edocumentation/embeddings.proto\x12\x18documentation.embeddings"\x1c\n\x0cEmbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t""\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x022\xd3\x01\n\x10EmbeddingService\x12]\n\nEmbedQuery\x12&.documentation.embeddings.EmbedRequest\x1a\'.documentation.embeddings.EmbedResponse\x12`\n\rEmbedDocument\x12&.documentation.embeddings.EmbedRequest\x1a\'.documentation.embeddings.EmbedResponseB \xaa\x02\x1dDocumentation.Embeddings.Grpcb\x06proto3'
)
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "documentation.embeddings_pb2", globals())
